passion-project/Models/AppointmentSystem/Doctor.cs
using System;
using System.Collections.Generic;

namespace passion_project.Models.AppointmentSystem
{
    public partial class Doctor
    {
        public Doctor()
        {
            DoctorPatient = new HashSet<DoctorPatient>();
        }

        public int DoctorId { get; set; }
        public string DoctorFirstName { get; set; }
        public string DoctorLastName { get; set; }
        public string Speciality { get; set; }
        public string DoctorImageUrl { get; set; }
        public string DoctorPhoneNumber { get; set; }
        public string DoctorEmailAddress { get; set; }
        public int? RoomNumber { get; set; }
        public string Biography { get; set; }

        public virtual ICollection<DoctorPatient> DoctorPatient { get; set; }
    }
}

passion-project/Models/HealthCenter/Doctor.cs
using System;
using System.Collections.Generic;

namespace passion_project.Models.HealthCenter
{
    public partial class Doctor
    {
        public Doctor()
        {
            Appointment = new HashSet<Appointment>();
        }

        public int DoctorId { get; set; }
        public string DoctorFirstName { get; set; }
        public string DoctorLastName { get; set; }
        public string Speciality { get; set; }
        public string DoctorImageUrl { get; set; }
        public string DoctorPhoneNumber { get; set; }
        public string DoctorEmailAddress { get; set; }
        public int? RoomNumber { get; set; }
        public string Biography { get; set; }

        public virtual ICollection<Appointment> Appointment { get; set; }
    }

}

passion-project/Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using passion_project.Models;
using passion_project.Models.HealthCenter;
using passion_project.Repository;
using passion_project.Services;
using passion_project.ViewModel.Appointment;

namespace passion_project.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly EmailSettings _emailSettings;

        public AppointmentController(ApplicationDbContext context, IOptions<EmailSettings> emailSettings)
        {
            _context = context;
            _emailSettings = emailSettings.Value;
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Index(string lastName)
        {
            AppointmentRepository appointmentRepo = new AppointmentRepository(_context);
            return View(appointmentRepo.GetAllAppointments(lastName));
        }

        public IActionResult GetAppointmentsByDoctorId(int id, string lastName)
        {
            AppointmentRepository appointmentRepo = new AppointmentRepository(_context);
            if(lastName == null)
            {
                return View(appointmentRepo.GetAppointmentsByDoctorId(id).ToList());
            }
            else
            {
                return View(appointmentRepo.GetAppointmentsByPatientLastName(id, lastName).ToList());
            }
        }

        public IActionResult GetAppointmentsByPatientId(int id, string lastName)
        {
            AppointmentRepository appointmentRepo = new AppointmentRepository(_context);
            if(lastName == null)
            {
                return View(appointmentRepo.GetAppointmentsByPatientId(id).ToList());
            }
            else
            {
                return View(appointmentRepo.GetAppointmentsByDoctorLastName(id, lastName).ToList());
            }
            
        }

        // GET: Appointment/Details/5
        public IActionResult Details(int id)
        {
            AppointmentRepository appointmentRepo = new AppointmentRepository(_context);
            if (appointmentRepo.Details(id) == null)
            {
                return NotFound();
            }
            return View(appointmentRepo.Details(id));
        }

        // GET: Appointment/Create
        [HttpGet]
        [Authorize]
        public IActionResult Create(int id)
        {
            AppointmentRepository appointmentRepo = new AppointmentRepository(_context);
            ViewBag.timeAvailable = new SelectList(String.Empty);
            
            var doctor = _context.Doctor.Where(d => d.DoctorId == id).FirstOrDefault();

            if (User.IsInRole("Admin"))
            {
                AppointmentVM appointmentModel = new AppointmentVM
                {
                    DoctorFirstName = doctor.DoctorFirstName,
                    DoctorLastName = doctor.DoctorLastName
                };
                return View(appointmentModel);
            }
            else
            {
                var userName = User.Identity.Name;
                var patient = _context.Patient.Where(p => p.PatientEmailAddress == userName).FirstOrDefault();
                if(patient == null)
                {
                    return RedirectToAction("Create", "Patient");
                }
                ViewBag.PatientFirstName = patient.PatientFirstName;
                ViewBag.PatientLastName = patient.PatientLastName;
                AppointmentVM appointmentModel = new AppointmentVM
                {
                    
                    PatientId = patient.PatientId,
                    PatientEmailAddress = userName,
                    PatientFirstName = patient.PatientFirstName,
                    PatientLastName = patient.PatientLastName,
                    DoctorFirstName = doctor.DoctorFirstName,
                    DoctorLastName = doctor.DoctorLastName
                };
                return View(appointmentModel);
            }
        }

        // POST: Appointment/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Create(AppointmentVM appointmentVM, int id)
        {
            if (ModelState.IsValid)
            {
                AppointmentRepository appointmentRepo = new AppointmentRepository(_context);
                if (new EmailHelper(_emailSettings).SendMail(appointmentVM.PatientEmailAddress, "Appointment Reminder", appointmentVM))
                {
                    if (appointmentRepo.CreateAppointment(appointmentVM, id))
                    {
                        if (User.IsInRole("Admin"))
                        {
                            return RedirectToAction("GetAppointmentsByDoctorId", new { id = id });
                        }
                        else
                        {
                            return RedirectToAction("GetAppointmentsByPatientId", new { id = appointmentVM.PatientId });
                        }
                    }

                }
            }
            ViewBag.PatientFirstName = appointmentVM.PatientFirstName;
            ViewBag.PatientLastName = appointmentVM.PatientLastName;
            return View(appointmentVM);
        }

        // GET: Appointment/Edit/5
        public IActionResult Edit(int id)
        {
            AppointmentRepository appointmentRepo = new AppointmentRepository(_context);
            var appointment = appointmentRepo.GetAppointment(id);
            var patient = _context.Patient.Where(p => p.PatientId == appointment.PatientId).FirstOrDefault();
            if (appointment == null)
            {
                return NotFound();
            }
            var appointmentVM = new AppointmentVM
            {
                DoctorId = appointment.DoctorId, 
                PatientFirstName = patient.PatientFirstName,
                PatientLastName = patient.PatientLastName, 
                AppointmentId = appointment.AppointmentId,
                AppointmentDate = appointment.AppointmentDate,
                AppointmentTime = appointment.AppointmentTime,
                AppointmentSummery = appointment.AppointmentSummery
            };
            return View(appointmentVM);
        }

        // POST: Appointment/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, AppointmentVM appointmentVM)
        {
            AppointmentRepository appointmentRepo = new AppointmentRepository(_context);
            var appointment = appointmentRepo.GetAppointment(id);
            if (id != appointmentVM.AppointmentId)
            {
                return NotFound();
            }
           
            if(appointmentRepo.UpdateAppointment(appointmentVM)) 
                return RedirectToAction("GetAppointmentsByDoctorId", new { id = appointment.DoctorId});
           
            return View(appointmentVM);
        }

        // GET: Appointment/Delete/5
        public IActionResult Delete(int id)
        {
            AppointmentRepository appointmentRepo = new AppointmentRepository(_context);
            var appointment = appointmentRepo.GetAppointment(id);
            var patient = _context.Patient.Where(p => p.PatientId == appointment.PatientId).FirstOrDefault();
            var doctor = _context.Doctor.Where(d => d.DoctorId == appointment.DoctorId).FirstOrDefault();
            if (appointment == null)
            {
                return NotFound();
            }

            var appointmentVM = new AppointmentVM
            {
                DoctorId = appointment.DoctorId,
                PatientFirstName = patient.PatientFirstName,
                PatientLastName = patient.PatientLastName,
                DoctorFirstName = doctor.DoctorFirstName,
                DoctorLastName = doctor.DoctorLastName,
                AppointmentDate = appointment.AppointmentDate,
                AppointmentTime = appointment.AppointmentTime
            };
            return View(appointmentVM);
        }

        // POST: Appointment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            AppointmentRepository appointmentRepo = new AppointmentRepository(_context);
            var appointment = appointmentRepo.GetAppointment(id);
            if (appointmentRepo.DeleteAppointment(id))
                return RedirectToAction("Index");
            return View(appointment);
        }

        public IEnumerable<TimeSpan> GetAvailableTime(int id, DateTime selectedDate)
        {
            AppointmentRepository appointmentRepo = new AppointmentRepository(_context);
            IEnumerable<TimeSpan> ts = appointmentRepo.GetAllTime().Except(appointmentRepo.GetAllBookedTime(id, selectedDate));
            return ts;
        }

    }

}

passion-project/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Mvc;
using passion_project.Models.HealthCenter;
using passion_project.Repository;
using passion_project.ViewModel;

namespace passion_project.Controllers
{
    public class DoctorController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly HostingEnvironment _hostingEnviroment;

        public DoctorController(ApplicationDbContext context, HostingEnvironment hostingEnviroment)
        {
            _context = context;
            _hostingEnviroment = hostingEnviroment;
        }
        public IActionResult Index(string speciality)
        {
            DoctorRepository doctorRepo = new DoctorRepository(_context, _hostingEnviroment);
            if (speciality == null)
            {
                return View(doctorRepo.GetAllDoctors());
            }
            else
            {
                return View(doctorRepo.GetDoctorsBySpeciality(speciality));
            }
            
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(DoctorCreateVM doctorModel)
        {
            DoctorRepository doctorRepo = new DoctorRepository(_context, _hostingEnviroment);
            if (ModelState.IsValid)
            {
                if (doctorRepo.Create(doctorModel))
                {
                    if (User.IsInRole("Admin"))
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
            }
            return View(doctorModel);
        }

        public IActionResult Edit(int id)
        {
            DoctorRepository doctorRepo = new DoctorRepository(_context, _hostingEnviroment);
            var doctor = doctorRepo.GetDoctor(id);
            if (doctor == null)
            {
                return NotFound();
            }
            DoctorIndexVM doctorModel = new DoctorIndexVM
            {
                DoctorId = doctor.DoctorId,
                DoctorFirstName = doctor.DoctorFirstName,
                DoctorLastName = doctor.DoctorLastName,
                ImageUrl = doctor.DoctorImageUrl,
                Speciality = doctor.Speciality,
                DoctorPhoneNumber = doctor.DoctorPhoneNumber,
                DoctorEmailAddress = doctor.DoctorEmailAddress,
                RoomNumber = doctor.RoomNumber,
                Biography = doctor.Biography

            };
            return View(doctorModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, DoctorIndexVM doctorModel)
        {
            DoctorRepository doctorRepo = new DoctorRepository(_context, _hostingEnviroment);
            if (doctorRepo.Update(id, doctorModel))
            {
                return RedirectToAction("Details", new { id = id });
            }
            return View(doctorModel);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            DoctorRepository doctorRepo = new DoctorRepository(_context, _hostingEnviroment);
            if (doctorRepo.Details(id) == null)
            {
                return NotFound();
            }
            return View(doctorRepo.Details(id));
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            DoctorRepository doctorRepo = new DoctorRepository(_context, _hostingEnviroment);
            var doctor = doctorRepo.GetDoctor(id);
            DoctorIndexVM doctorModel = new DoctorIndexVM
            {
                DoctorId = doctor.DoctorId,
                DoctorFirstName = doctor.DoctorFirstName,
                DoctorLastName = doctor.DoctorLastName
            };
            return View(doctorModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(DoctorIndexVM doctorModel)
        {
            DoctorRepository doctorRepo = new DoctorRepository(_context, _hostingEnviroment);
            if (doctorModel == null)
            {
                return NotFound();
            }
            if(doctorRepo.Delete(doctorModel))
            {
                return RedirectToAction("Index");
            }
            return View(doctorModel);
        }

    }
 }

passion-project/Views/Doctor/Create.cshtml
@model passion_project.ViewModel.DoctorCreateVM

@{
    ViewData["Title"] = "Create";
}


<div class="container create-doctor mt-5 mb-5">
    <div class="card border-info p-3 box-shadow">
        @if (!User.IsInRole("Admin"))
        {
            <h4 class="alert-heading mb-5">Create your profile</h4>
        }
        <form method="post" enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="form-group col-md-6 col-sm-12">
                    <h6>First Name:</h6>
                    <input asp-for="DoctorFirstName" class="form-control" />
                    <span asp-validation-for="DoctorFirstName" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <h6>Last Name:</h6>
                    <input asp-for="DoctorLastName" class="form-control" />
                    <span asp-validation-for="DoctorLastName" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col">
                    <h6>Image File:</h6>
                    <input asp-for="ImageFile" type="file" value="Upload" />
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6 col-sm-12">
                    <h6>Speciality:</h6>
                    <input asp-for="Speciality" class="form-control" />
                    <span asp-validation-for="Speciality" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <h6>Room No.:</h6>
                    <input asp-for="RoomNumber" class="form-control" />
                    <span asp-validation-for="RoomNumber" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6 col-sm-12">
                    <h6>Phone No.:</h6>
                    <input asp-for="DoctorPhoneNumber" class="form-control" />
                    <span asp-validation-for="DoctorPhoneNumber" class="text-danger"></span>
                </div>
                @if (User.IsInRole("Admin"))
                {
                    <div class="form-group col-md-6 col-sm-12">
                        <h6>Email Address:</h6>
                        <input asp-for="DoctorEmailAddress" class="form-control" />
                        <span asp-validation-for="DoctorEmailAddress" class="text-danger"></span>
                    </div>
                }
                else
                {
                    <div class="form-group col-md-6 col-sm-12">
                        <h6>Email Address:</h6>
                        <input asp-for="DoctorEmailAddress" class="form-control" value="@User.Identity.Name" />
                        <span asp-validation-for="DoctorEmailAddress" class="text-danger"></span>
                    </div>
                }
            </div>
            <div class="row">
                <div class="form-group col">
                    <h6>Biography:</h6>
                    <textarea asp-for="Biography" class="form-control" rows="3" stye="width:100%;"></textarea>
                    <span asp-validation-for="Biography" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

passion-project/Views/Doctor/Delete.cshtml
@model passion_project.ViewModel.DoctorIndexVM

@{
    ViewData["Title"] = "Delete";
}

<style>
    .delete {
        display: block;
        margin: 210px auto;
        padding: 50px;
        line-height: 4;
    }
</style>

<div class="container">
    <div class="card border-info delete">
        <h3 class="text-center">Are you sure you want to delete @Model.DoctorFirstName @Model.DoctorLastName ? </h3>
        <small class="text-center">Make sure to cancle all this doctor`s appointments first.</small>
        <form asp-action="Delete" class="text-center">
            <input type="hidden" asp-for="DoctorId" />
            <input type="submit" value="Delete" class="btn btn-info" />
            <a asp-action="Index" class="btn btn-info">Back to List</a>
        </form>
    </div>
</div>

passion-project/Views/Doctor/Details.cshtml
@model passion_project.ViewModel.DoctorIndexVM

@{
    ViewData["Title"] = "Details";
}

<style>
    .breadcrumb-item li{
        font-size: 16px;
    }
    .breadcrumb-item a {
        color: #17a2b8;
    }

    .fa-edit, .fa-trash-alt {
        color: white;
        font-size: 18px;
    }
    
    .col img {
        display: block;
        margin: 10px auto;
    }
</style>
<div class="container mt-3 mb-5">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-white">
            <li class="breadcrumb-item"><a asp-controller="Doctor" asp-action="Index" asp-route-id="@Model.DoctorId">Doctors</a></li>
            <li class="breadcrumb-item active" aria-current="page">@Model.DoctorFirstName @Model.DoctorLastName</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col">
            <img src="@Url.Content(Model.ImageUrl)" class="card-img" alt="doctor-photo" style=" width:400px" />
        </div>
        <div class="col mt-5 mt-lg-0">
            <div class="card border-info p-3">
                <div class="card-header bg-info text-white">
                    <div class="d-flex justify-content-between mb-2">
                        <h4>@Model.DoctorFirstName @Model.DoctorLastName</h4>
                        <div>
                            @if (User.IsInRole("Admin") || (User.Identity.Name == Model.DoctorEmailAddress))
                            {
                                <a asp-action="Edit" asp-route-id="@Model.DoctorId"><i class="far fa-edit"></i></a>
                            }
                            @if (User.IsInRole("Admin"))
                            {
                                <a asp-action="Delete" asp-route-id="@Model.DoctorId"><i class="fas fa-trash-alt"></i></a>
                            }
                        </div>
                    </div>
                </div>
                <div class="card-body p-3 box-shadow">
                    <h6>Speciality : @Model.Speciality</h6>
                    <h6>Room No. : @Model.RoomNumber</h6>
                    <h6>Phone No.: @Model.DoctorPhoneNumber</h6>
                    <h6> Email Address : @Model.DoctorEmailAddress</h6>
                    <div class="card-body border-info p-3">
                        <h4>Biography</h4><hr />
                        <p>@Model.Biography</p>
                    </div>
                    @if ((User.Identity.Name != Model.DoctorEmailAddress) && !User.IsInRole("Admin"))
                    {
                      
                        <a asp-controller="Appointment" asp-action="Create" asp-route-id="@Model.DoctorId" class="btn btn-info">MAKE APPOINTMENT </a>
                    }
                    else if (User.Identity.Name == Model.DoctorEmailAddress)
                    {
                        <a asp-controller="Appointment" asp-action="GetAppointmentsByDoctorId" asp-route-id="@Model.DoctorId" class="btn btn-info">Get Appointments</a>
                    }
                    else if (User.IsInRole("Admin"))
                    {
                        <div class="row">
                            <div class="col-lg-12 col-md-12 mb-2">
                                <a asp-controller="Appointment" asp-action="Create" asp-route-id="@Model.DoctorId" class="btn btn-info">Make An Appointment</a>
                            </div>
                            <div class="col-lg-12 col-md-12 mb-2">
                                <a asp-controller="Appointment" asp-action="GetAppointmentsByDoctorId" asp-route-id="@Model.DoctorId" class="btn btn-info">Get Appointments</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

</div>

passion-project/Views/Doctor/Edit.cshtml
@model passion_project.ViewModel.DoctorIndexVM

@{
    ViewData["Title"] = "Edit";
}

<style>
    .breadcrumb-item li{
        font-size: 16px;
    }
    .breadcrumb-item a{
        color:#5bc0de;
    }
</style>

    <div class="container mt-3 mb-5">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-white">
                @if (User.IsInRole("Admin"))
                {
                    <li class="breadcrumb-item"><a asp-controller="Doctor" asp-action="Index" asp-route-id="@Model.DoctorId">Doctors</a></li>
                    <li class="breadcrumb-item active" aria-current="page">@Model.DoctorFirstName @Model.DoctorLastName</li>
                }

            </ol>
        </nav>
        <div class="row">
            <div class="col">
                <img src="@Url.Content(Model.ImageUrl)" class="card-img" alt="doctor-photo" style=" width:400px" />
            </div>
            <div class="col mt-5 mt-lg-0">
                <div class="card border-info p-3 doctor-edit">
                    <div class="card-header bg-info text-white">
                        <h4>@Model.DoctorFirstName @Model.DoctorLastName</h4>
                    </div>
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="card-body p-3 box-shadow" style="line-height:3;">
                            @if (User.IsInRole("Admin"))
                            {
                                <div class="form-group">
                                    <h6>Email Address:</h6>
                                    <input asp-for="DoctorEmailAddress" class="form-control" />
                                    <span asp-validation-for="DoctorEmailAddress" class="text-danger"></span>
                                </div>
                            }
                            else
                            {
                                <div class="form-group">
                                    <h6>Email Address:</h6>
                                    <input asp-for="DoctorEmailAddress" class="form-control" readonly />
                                    <span asp-validation-for="DoctorEmailAddress" class="text-danger"></span>
                                </div>
                            }
                            <div class="form-group">
                                <h6>Phone N0.:</h6>
                                <input asp-for="DoctorPhoneNumber" class="form-control" />
                                <span asp-validation-for="DoctorPhoneNumber" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <h6>Room No.:</h6>
                                <input asp-for="RoomNumber" class="form-control" />
                                <span asp-validation-for="RoomNumber" class="text-danger"></span>
                            </div>
                            <div class="row">
                                <div class="form-group col">
                                    <h6>Biography:</h6>
                                    <textarea asp-for="Biography" class="form-control" rows="3" stye="width:100%;"></textarea>
                                    <span asp-validation-for="Biography" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Save" class="btn btn-info" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

passion-project/Views/Doctor/Index.cshtml
@model IEnumerable<passion_project.ViewModel.DoctorIndexVM>

@{
    ViewData["Title"] = "List Of Doctors";
}

<style>
     .fa-plus, .fa-search {
        color: #17a2b8
     }
    
</style>

<div class="container mb-5 mt-5">
    @if (User.IsInRole("Admin"))
    {
        <div class="row mb-3">
            <div class="col">
                <a asp-action="Create"><i class="fas fa-plus float-right"></i></a>
            </div>
        </div>
    }
    <form class="form-inline" asp-controller="Doctor" asp-action="Index">
        <div class="input-group mb-3" style="width:100%;">
            <div class="input-group-prepend">
                <button type="submit" class="btn btn-outline-secondary"><i class="fas fa-search"></i></button>
            </div>
            <input type="text" class="form-control" placeholder="Search By Speciality"
                   aria-label="" aria-describedby="basic-addon1" name="speciality" />
        </div>
        <div class="row" style="width:100%;">
            @foreach (var item in Model)
            {
                <div class="col-lg-6 col-md-12 col-sm-12">
                    <div class="card border-info mt-3 mb-3" style="max-width: 540px;">
                        <div class="row no-gutters">
                            <div class="col-md-4">
                                <img src="@Url.Content(item.ImageUrl)" class="card-img" alt="doctor-photo" style="height: 250px;" />
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">@item.DoctorFirstName @item.DoctorLastName </h5>
                                    <p class="card-text">Speciality : @item.Speciality</p>
                                    <p class="card-text">Phone :  @item.DoctorPhoneNumber</p>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 m-2">
                                        <a asp-action="Details" asp-route-id="@item.DoctorId" class="btn btn-info">More Information</a>
                                        </div>
                                        <div class="col-lg-12 col-md-12 col-sm-12 m-2">
                                        <a asp-controller="Appointment" asp-action="Create" asp-route-id="@item.DoctorId" class="btn btn-info">Make An Appointment</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </form>
</div>