passion-project/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Mvc;
using passion_project.Models.HealthCenter;
using passion_project.Repository;
using passion_project.ViewModel;

namespace passion_project.Controllers
{
    public class DoctorController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly HostingEnvironment _hostingEnviroment;

        public DoctorController(ApplicationDbContext context, HostingEnvironment hostingEnviroment)
        {
            _context = context;
            _hostingEnviroment = hostingEnviroment;
        }
        public IActionResult Index(string speciality)
        {
            DoctorRepository doctorRepo = new DoctorRepository(_context, _hostingEnviroment);
            if (speciality == null)
            {
                return View(doctorRepo.GetAllDoctors());
            }
            else
            {
                return View(doctorRepo.GetDoctorsBySpeciality(speciality));
            }
            
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(DoctorCreateVM doctorModel)
        {
            DoctorRepository doctorRepo = new DoctorRepository(_context, _hostingEnviroment);
            if (ModelState.IsValid)
            {
                if (doctorRepo.Create(doctorModel))
                {
                    if (User.IsInRole("Admin"))
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
            }
            return View(doctorModel);
        }

        public IActionResult Edit(int id)
        {
            DoctorRepository doctorRepo = new DoctorRepository(_context, _hostingEnviroment);
            var doctor = doctorRepo.GetDoctor(id);
            if (doctor == null)
            {
                return NotFound();
            }
            DoctorIndexVM doctorModel = new DoctorIndexVM
            {
                DoctorId = doctor.DoctorId,
                DoctorFirstName = doctor.DoctorFirstName,
                DoctorLastName = doctor.DoctorLastName,
                ImageUrl = doctor.DoctorImageUrl,
                Speciality = doctor.Speciality,
                DoctorPhoneNumber = doctor.DoctorPhoneNumber,
                DoctorEmailAddress = doctor.DoctorEmailAddress,
                RoomNumber = doctor.RoomNumber,
                Biography = doctor.Biography

            };
            return View(doctorModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, DoctorIndexVM doctorModel)
        {
            DoctorRepository doctorRepo = new DoctorRepository(_context, _hostingEnviroment);
            if (doctorRepo.Update(id, doctorModel))
            {
                return RedirectToAction("Details", new { id = id });
            }
            return View(doctorModel);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            DoctorRepository doctorRepo = new DoctorRepository(_context, _hostingEnviroment);
            if (doctorRepo.Details(id) == null)
            {
                return NotFound();
            }
            return View(doctorRepo.Details(id));
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            DoctorRepository doctorRepo = new DoctorRepository(_context, _hostingEnviroment);
            var doctor = doctorRepo.GetDoctor(id);
            DoctorIndexVM doctorModel = new DoctorIndexVM
            {
                DoctorId = doctor.DoctorId,
                DoctorFirstName = doctor.DoctorFirstName,
                DoctorLastName = doctor.DoctorLastName
            };
            return View(doctorModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(DoctorIndexVM doctorModel)
        {
            DoctorRepository doctorRepo = new DoctorRepository(_context, _hostingEnviroment);
            if (doctorModel == null)
            {
                return NotFound();
            }
            if(doctorRepo.Delete(doctorModel))
            {
                return RedirectToAction("Index");
            }
            return View(doctorModel);
        }

    }
 }

passion-project/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Mvc;
using passion_project.Models.HealthCenter;
using passion_project.Repository;
using passion_project.ViewModel.Patient;

namespace passion_project.Controllers
{
    [Authorize]
    public class PatientController : Controller
    {
        private readonly ApplicationDbContext _context;


        public PatientController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        // GET: Patients
        public IActionResult Index(string sortOrder)
        {
            string sort = String.IsNullOrEmpty(sortOrder) ? "name-asc" : sortOrder;
            PatientRepository patientRepo = new PatientRepository(_context);
            return View(patientRepo.GetAll(sort));           
        }
        
        // GET: Patients/Details/5
        public IActionResult Details(int id)
        {
            PatientRepository patientRepo = new PatientRepository(_context);
            if (patientRepo.Details(id) == null)
            {
                return NotFound();
            }

            return View(patientRepo.Details(id));
        }

        // GET: Patients/Create
        public IActionResult Create()
        {
            var userName = User.Identity.Name;
            if (User.IsInRole("Admin"))
            {
                return View();
            }
            else
            {
                PatientVM patientModel = new PatientVM
                {
                    
                    PatientEmailAddress = userName
                   
                };
                return View(patientModel);
            }
        }

        // POST: Patients/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PatientVM patientModel)
        {
            PatientRepository patientRepo = new PatientRepository(_context);
            if (ModelState.IsValid)
            {
                if (patientRepo.CreatePatient(patientModel))
                {
                    if (User.IsInRole("Admin"))
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }

            }
            return View(patientModel);
        }

        // GET: Patients/Edit/5
        public IActionResult Edit(int id)
        {
            PatientRepository patientRepo = new PatientRepository(_context);
            var patient = patientRepo.GetPatient(id);
            if (patient == null)
            {
                return NotFound();
            }
            PatientVM patientModel = new PatientVM
            {
                PatientId = patient.PatientId,
                PatientFirstName = patient.PatientFirstName,
                PatientLastName = patient.PatientLastName,
                Phn = patient.Phn,
                PatientPhoneNumber = patient.PatientPhoneNumber,
                PatientEmailAddress = patient.PatientEmailAddress,
                PatientAddress = patient.PatientAddress,
                PatientCity = patient.PatientCity,
                PatientPostalCode = patient.PatientPostalCode,
                PatientHistory = patient.PatientHistory
            };
            return View(patientModel);
        }

        // POST: Patients/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, PatientVM patientModel)
        {
            PatientRepository patientRepo = new PatientRepository(_context);
            if (id != patientModel.PatientId)
            {
                return NotFound();
            }
            if (patientRepo.Update(id, patientModel))
            {
                return RedirectToAction("Details", new { id = id });
            }
            return View(patientModel);
        }

        // GET: Patients/Delete/5
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            PatientRepository patientRepo = new PatientRepository(_context);
            var patient = patientRepo.GetPatient(id);
            if (patient == null)
            {
                return NotFound();
            }
            PatientVM patientModel = new PatientVM
            {
                PatientId = patient.PatientId,
                PatientFirstName = patient.PatientFirstName,
                PatientLastName = patient.PatientLastName
            };
            return View(patientModel);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(PatientVM patientModel)
        {
            PatientRepository patientRepo = new PatientRepository(_context);
            if(patientRepo.Delete(patientModel))
            {
                return RedirectToAction("Index");
            }
            return View(patientModel);
        }

    }
}

passion-project/Views/Shared/_AdminPartial.cshtml
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="Patient" asp-action="Index">Patients</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="Doctor" asp-action="Index">Doctors</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="Appointment" asp-action="Index">Appointments</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="UserRole" asp-action="Create">User Role</a>
    </li>
}

passion-project/Views/Shared/_DoctorPartial.cshtml
@using passion_project.Models.HealthCenter
@inject ApplicationDbContext _context

@{
    var doctor = _context.Doctor.FirstOrDefault(p => p.DoctorEmailAddress == @User.Identity.Name);
}

@if (User.Identity.IsAuthenticated && User.IsInRole("Doctor"))
{
    if (doctor == null)
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Doctor" asp-action="Create">Profile</a>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Doctor" asp-action="Details" asp-route-id="@doctor.DoctorId">Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Appointment" asp-action="GetAppointmentsByDoctorId" asp-route-id="@doctor.DoctorId">Appointments</a>
        </li>
    }

}

passion-project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Health Care Center</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        .content{
            min-height:100%;
        }
        footer{
           background-color:lightgray;
        }
        .fa-phone-square{
            color:#17a2b8;
        }
        .fa-at{
            color:#17a2b8;
        }
        
    </style>
</head>
<body class="wrapper d-flex flex-column min-vh-100 align-self-stretch">
    <header class="flex-shrink-0">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white box-shadow ">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img alt="profile-logo" src="@Url.Content("/images/profile.png")" style="width:50px; height:50px;"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (!User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        }

                        <partial name="_AdminPartial" />
                        <partial name="_PatientPartial" />
                        <partial name="_DoctorPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="flex-grow-1 flex-shrink-0">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="content ">
            @RenderBody()
        </main>
    </div>

    <footer class="flex-shrink-0">
        <div class="container pt-3">
            <div class="row">
                <div class="col">
                    <h6>Address:</h6>
                    <p>3308 Ash St Vancouver BC V5Z 3E3</p>
                    <i class="fas fa-phone-square"></i> (604) 688-5225<br />
                    <i class="fas fa-at"></i> info@healthcenter.ca
                </div>
                <div class="col">
                    <h6>Opening hours:</h6>
                    <p>Monday-Friday 10am-6pm</p>
                    <p>Saturday, Sunday Close</p>
                </div>
            </div>
            <div class="border-top text-center p-2 pb-5">
                &copy; 2020 - Zhaleh Sojoodi
            </div>
        </div>

    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    @RenderSection("Scripts", required: false)
 
</body>
</html>

passion-project/Views/Shared/_PatientPartial.cshtml
@using passion_project.Models.HealthCenter
@inject ApplicationDbContext _context

@{
    var patient = _context.Patient.FirstOrDefault(p => p.PatientEmailAddress == @User.Identity.Name);
}


@if (User.Identity.IsAuthenticated && !User.IsInRole("Admin") && !User.IsInRole("Doctor"))
{
    if (patient == null)
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Patient" asp-action="Create">Profile</a>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Patient" asp-action="Details" asp-route-id="@patient.PatientId">Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Doctor" asp-action="Index">Doctors</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Appointment" asp-action="GetAppointmentsByPatientId" asp-route-id="@patient.PatientId">Appointments</a>
        </li>
    }


}